### ISSUE TITLE
Bugs in "--- source code" handling

### ISSUE THREAD

**Issue by AugustM** [mangini/gdocs2md#10]
There are still some bugs in the "--- source code" function:
- All lines are indented four spaces, EXCEPT some are not.
- Blank lines in the source are lost (mostly). These can be important for breaking up blocks of meaning.

Example files have been sent by private email.

**Comment by mangini** [comment]
The blank lines issue was fixed already (see issue #7). The indentation bug was caused by misplaced ^M invisible characters in the source (probably caused by pasting code in Windows - TIP: always use shift+ctrl+V to paste without format)

**Comment by AugustM** [comment]
Thanks. I had no control over the source file. However, your note lets me know I can fix it by copying the block of code and then repasting it with Ctrl+Shift+V. Thanks.
