### ISSUE TITLE
Cannot call method "getActiveSection"

### ISSUE THREAD

**Issue by reggi** [mangini/gdocs2md#12]
Getting this error when I run after authenticating.

```
TypeError: Cannot call method "getActiveSection" of null. (line 2, file "Code")
```

I also can't see the script in the scripts manager.

**Comment by mangini** [comment]
Are you sure you are running it inside a Google Drive _Document_? Because it doesn't work for Presentation and Spreadsheets.

If you can share a document with this error with me, it is easy for me to check.

**Comment by reggi** [comment]
It is a document. You want me to share the script or the doc?

**Comment by mangini** [comment]
The minimum doc that gives an error (I don't want to see any private information in your doc, so please remove anything that might contain personal/private info). My email is the same as my github name, domain gmail.com

**Comment by reggi** [comment]
That error is coming from the script itself (shared).

![screen shot 2013-06-11 at 1 02 41 pm](https://f.cloud.github.com/assets/296798/638301/dd79f354-d2b8-11e2-8fdb-75beafca9633.png)

**Comment by mangini** [comment]
How did you open the Script Editor? As per the instructions, you need to open it from an existing Document (Tools -> Script Editor).  Looking at the tabs you have opened, I don't see any Document there. It can be in another window, but that's something to check anyway, since the error is quite the same if you happen to not have the document opened when executing the script.

**Comment by reggi** [comment]
If I go to Tools -> Script Editor it sends me to the following screenshot:

![screen shot 2013-06-11 at 1 57 06 pm](https://f.cloud.github.com/assets/296798/638596/81b427b2-d2c0-11e2-86da-0710382cb090.png)

**Comment by reggi** [comment]
I just got it working I had to "Create script for" Document.

**Comment by reggi** [comment]
Is there anyway for you to publish the app? To make this easier?
