### ISSUE TITLE
Enable batch editing files

### ISSUE THREAD

**Issue by minthemiddle** [mangini/gdocs2md#14]
The script should be applicable to more than one document at a time. Right now one needs to copy and paste the script to every new document one wants to convert. It should be possible to batch convert files from GDrive.

**Comment by mangini** [comment]
This is a great idea. I don't think I will have time to implement it in the near future. If you or anyone else wants to submit a pull request, I will be happy to evaluate and accept.

**Comment by lpanebr** [comment]
I do plan on adding this in the coming months (maybe sooner..).

It will then be a stand alone script where the user will be able to:
- select source document
- select output format (markdown or html)
- select target to exported files (e-mail address or google drive folder)

**Comment by pbolger** [comment]
This would certainly make my life easier.

**Comment by suntong** [comment]
Waiting for your changes lpanebr!

**Comment by suntong** [comment]
What happened @minthemiddle, is it fixed now?
