### ISSUE TITLE
Code Block "--- source code" only handles indented lines

### ISSUE THREAD

**Issue by AugustM** [mangini/gdocs2md#5]
As far as I can tell, only the lines between "--- source code" and "---" which 
are ALREADY indented by four spaces are getting turned into "pre" code. 
[This system didn't like me using anglebrackets around "pre".]

Thus a block of code that has some lines fully exdented and some lines indented 
gets turned into paragraphs for the exdented lines and "pre" blocks for the indented 
lines, alternating through the block, up to the ---. 

I have not tried what happens to normal paragraphs, outside the --- source code 
block, that are indented by 4 spaces.

It worked earlier today and I have been getting the script from github each time 
I use it so it is likely caused by recent work.

**Comment by mangini** [comment]
Can't repro. Please, send (via email) a sample doc with the problem.

**Comment by mangini** [comment]
invalid bug (using "-- sample code" instead of "--- source code")

**Comment by AugustM** [comment]
Thanks. Oops.
